### ISSUE TITLE
Implement OCR fallback

### ISSUE THREAD

**Issue by Dids** [Didstopia/PDFReader#13]
# Task list for OCR support

### Primary tasks

- [ ] Port [Tesseract .NET](https://github.com/charlesw/tesseract) to .NET Standard 2.0
- [ ] Include both [Tesseract](https://github.com/tesseract-ocr/tesseract/blob/master/LICENSE) and [Tesseract .NET](https://github.com/charlesw/tesseract/blob/master/LICENSE.txt) licenses and add proper attributions

### Secondary tasks

- [ ] [Export images](http://www.pdfsharp.net/wiki/ExportImages-sample.ashx) when a page is empty (`ExtractText()` returns an empty string)
- [ ] [Improve the quality of exported images](https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality)
- [ ] [Build](https://github.com/tesseract-ocr/tesseract/wiki/Compiling) and include `tessdata` for as many languages as possible (optionally create NuGet packages for each language, so the user of this library can pick and choose whichever they want?)
